# Meta.TypeMeta
apiVersion: compute.controller.com/v1
kind: Ec2Instance

# Meta.ObjectMeta
metadata:
  labels:
    app.kubernetes.io/name: kube-controller
    app.kubernetes.io/managed-by: kustomize
  name: ec2instance-sample
# Instance spec
spec:
  # TODO(user): Add fields here
  amiID: mydummyamiID
  sshKey: my-keypair
  type: t3-micro
  storage:
    standard:
      size: 10Gi
    fast:
      size: 50Gi

# Status and other information specific to the instance
status:
  phase: Running

 